language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - pypy
env:
  - DJANGO=1.8
install:
  - pip install flake8 pep8
  - pip list
  - flake8 --version
before_script:
  - flake8 .
script:
  - python manage.py test
matrix:
  allow_failures:
    - python: pypy
