language: python
python:
    - 2.7
services: postgresql
env:
    - DJANGO=1.8
install:
    - pip install flake8 --quiet
    - pip install psycopg2 --quiet
    - pip install -q Django==$DJANGO --quiet
    - pip install pyunpack --quiet
before_script:
    - psql -c "CREATE DATABASE testDB;" -U postgres
    - python manage.py migrate
script:
    - flake8 .
    - python manage.py test
